version: '3.8'

services:
  web.client:
    container_name: web.client
    build:
      context: .
      dockerfile: Web/ClientApp/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    depends_on:
      - api.catalog
      - identityserver
    ports:
      - 5000:5000
       
  web.admin:
    container_name: web.admin
    build:
      context: .
      dockerfile: Web/AdminApp/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
    depends_on:
      - api.catalog
      - identityserver
    ports:
      - 5001:5001
 
  api.catalog:
    container_name: api.catalog
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.Host/Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:5002
    depends_on:
        - postgres
    ports:
        - 5002:5002

  api.basket:
    container_name: api.basket
    build:
      context: .
      dockerfile: Services/Basket/Basket.Host/Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:5003
    depends_on:
        - redis
    ports:
        - 5003:5003

  api.order:
    container_name: api.order
    build:
      context: .
      dockerfile: Services/Order/Order.Host/Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:5004
    depends_on:
        - redis
    ports:
        - 5004:5004

  pgadmin4:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
        - PGADMIN_DEFAULT_EMAIL=user@mail.com
        - PGADMIN_DEFAULT_PASSWORD=postgres
    depends_on:
        - postgres
    ports:
        - 8001:80

  postgres:
    container_name: postgres
    image: postgres
    environment:
        - POSTGRES_PASSWORD=postgrespw
    ports:
        - 5433:5432

  redis:
    container_name: redis
    image: redis
    ports:
        - 6380:6379

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
        - 80:80
    volumes:
      - ./Proxy/gateway/nginx/conf.d:/etc/nginx/conf.d
      - ./Proxy/assets:/var/www/assets
    restart: always

networks:    
  default:
    driver: bridge
    internal: false
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.4/24
          gateway: 192.168.0.4