version: '3.8'

services:
  web.client:
    container_name: web.client
    build:
      context: .
      dockerfile: ./Web/ClientApp/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:3000
      - Authorization__Authority=http://www.alevelwebsite.com:5004
      - Api__CatalogUrl=http://www.alevelwebsite.com:5001/api/v1
      - Api__BasketUrl=http://www.alevelwebsite.com:5002/api/v1
      - Api__OrderUrl=http://www.alevelwebsite.com:5003/api/v1
      - Api__IdentityUrl=http://www.alevelwebsite.com:5004
      - Api__CallbackUrl=http://www.alevelwebsite.com:3000
      - Api__RedirectUri=http://www.alevelwebsite.com:3000/signin-oidc
      - Api__PostLogoutRedirectUri=http://www.alevelwebsite.com:3000/signout-callback-oidc
    depends_on:
      - api.catalog
      - api.basket
      - api.order
      - server.identity
    ports:
      - 3000:3000
  
  api.catalog:
    container_name: api.catalog
    build:
      context: .
      dockerfile: ./Services/Catalog/Catalog.Host/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
      - Authorization__Authority=http://www.alevelwebsite.com:5004
      - BaseUrl=http://www.alevelwebsite.com:5001
      - ConnectionStrings__DefaultConnection=server=www.alevelwebsite.com;port=5433;database=catalog;uid=postgres;password=postgrespw
    depends_on:
      - postgres
    ports:
      - 5001:5001

  api.basket:
    container_name: api.basket
    build:
      context: .
      dockerfile: ./Services/Basket/Basket.Host/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5002
      - Authorization__Authority=http://www.alevelwebsite.com:5004
      - BaseUrl=http://www.alevelwebsite.com:5002
      - Redis__Host=www.alevelwebsite.com:6380
      - Redis__CacheTimeout=00:30:00
    depends_on:
      - redis
    ports:
      - 5002:5002

  api.order:
    container_name: api.order
    build:
      context: .
      dockerfile: ./Services/Order/Order.Host/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5003
      - Authorization__Authority=http://www.alevelwebsite.com:5004
      - BaseUrl=http://www.alevelwebsite.com:5003
      - ConnectionStrings__DefaultConnection=server=www.alevelwebsite.com;port=5433;database=order;uid=postgres;password=postgrespw
    depends_on:
      - postgres
    ports:
      - 5003:5003

  server.identity:
    container_name: server.identity
    build:
      context: .
      dockerfile: ./Services/Identity/IdentityServer/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5004
      - WebClientUrl=http://www.alevelwebsite.com:3000
      - CatalogUrl=http://www.alevelwebsite.com:5001
      - BasketUrl=http://www.alevelwebsite.com:5002
      - OrderUrl=http://www.alevelwebsite.com:5003
      - ConnectionStrings__DefaultConnection=server=www.alevelwebsite.com;port=5433;database=identity;uid=postgres;password=postgrespw
    depends_on:
      - postgres
    ports:
      - 5004:5004

  pgadmin4:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@mail.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    depends_on:
      - postgres
    ports:
      - 8001:80

  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5433:5432

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6380:6379

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
    restart: always
    volumes:
      - ./Proxy/gateway/nginx/conf.d:/etc/nginx/conf.d
      - ./Proxy/assets:/var/www/assets

networks:
  default:
    driver: bridge
    internal: false
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.4/24
          gateway: 192.168.0.4