global using FluentAssertions;
global using Microsoft.Extensions.Logging;
global using Moq;
global using Xunit;
global using Microsoft.Extensions.Options;
global using StackExchange.Redis;
global using Basket.Host.Configurations;
global using Basket.Host.Services;
global using Basket.Host.Services.Interfaces;