// Packages
import Head from 'next/head';
// Components
import HomeView from '@/components/view/HomeView';

const HomePage = () => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <HomeView />
  </>
);

export default HomePage;
